apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-test-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';

      access_log    /var/log/nginx/access.log main;

      server {
          listen       80;
          server_name  _;

          location / {
              root   /etc/nginx/test;
              index  index.html index.htm;
          }
      }
    }
  test-min.html: |
    <head></head>

    <body>
        <h1>test ok</h1>
    </body>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-server
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx-test-server
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx-test-server
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-test-conf
          mountPath: "/etc/nginx/"
      volumes:
      - name: nginx-test-conf
        configMap:
          name: nginx-test-conf
          items:
            - key: nginx.conf 
              path: nginx.conf
            - key: test-min.html
              path: test/test-min.html
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
    selector:
        app: nginx-test-server
    ports:
        - port: 80
    type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-nodeport-service
spec:
    selector:
        app: nginx-test-server
    ports:
        - port: 80
          nodePort: 30060
    type: NodePort