apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-server
  revisionHistoryLimit: 2 # デフォルトは2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # 25% のようにパーセントでも指定可能
      maxUnavailable: 0 # maxSurge と同じくパーセントで指定可能
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx-server
        command:
        args:
        ports:
        - containerPort: 80
