apiVersion: v1
kind: Service
metadata:
    name: nginx-lb-service
spec:
    selector:
        app: nginx-test-server
    ports:
        - protocol: TCP
          port: 80
          nodePort: 32000
    type: LoadBalancer